### ISSUE TITLE
not working in android, not tested in ios

### ISSUE THREAD

**Issue by hasan642** [acurat/react-native-geofencing#2]
it is not notify user, even got in or go out boundary.
that is my code:

import React, { Component } from 'react';
import { Text, View } from 'react-native';

import Geofence, { Constants } from 'react-native-geolocation-monitor';

export default class App extends Component {
    subscription;

    componentDidMount() {
        Geofence.initialize({ requestPermission: true });

        Geofence.add({
            id: 'work',
            radius: 0.5,
            latitude: 31.9709184,
            longitude: 35.902259199999996,
        })
            .then(result => console.warn('11', result))
            .catch(error => console.warn(JSON.stringify(error)));

        try {
            console.log('111')
            this.subscription = Geofence.notify(result => {
                console.log('result is', result)
            })
        }
        catch (err) {
            console.log('err in geofence is', err)
        }
    }

    componentWillUnmount() {
        if (this.subscription) {
            this.subscription.remove();
        }
    }

    render() {
        return (
            <View
                style={{
                    flex: 1,
                    justifyContent: 'center',
                    alignItems: 'center',
                }}
            >
                <Text>Basic Usage!</Text>
            </View>
        );
    }
}

help plz !

**Comment by acurat** [comment]
The radius of 0.5 meters is very small. So it is hard for devices to detect in or out transitions. 
Try something bigger like 100-150m.

Checkout best practices in Android (there is a section about setting ideal radius) - https://developer.android.com/training/location/geofencing#BestPractices

**Comment by hasan642** [comment]
Radius was 50 but also not worked, how to test it plz.
And it is work in background ?

**Comment by acurat** [comment]
You can also mock the location on a real device. There are several apps for this such as Fake GPS location or Mockgeofix (https://play.google.com/store/apps/details?id=github.luv.mockgeofix). I use the latter. Follow the instructions on those app. On your device you will need to **Select mock location app** in **Developer Options**

I haven't had much luck testing reliably on emulators but certainly worth a try. See https://developer.android.com/guide/topics/location/strategies#MockGeo

It does not work in the background on Android, but I'm going to add that capability soon.

**Comment by hasan642** [comment]
Another question plz, in intallation document you say add import and create new object in get packages in main activity.
But i think must add in main application,
Right ?

**Comment by acurat** [comment]
Correct. I've fixed the documentation. Thanks for reporting the error.

**Comment by hasan642** [comment]
Thank you brother 1😄

**Comment by acurat** [comment]
I'm closing this, please create new issue if you have any trouble.
